#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
#系统调用实验修改8：增加系统调用的汇编指令入口，在usys.S中生成汇编指令
entry("getProcessNumber");
#内存管理实验修改12：增加测试系统调用的汇编指令入口，在usys.S中生成汇编指令
entry("testheapalloc");

entry("heapinit");
entry("heapalloc");
entry("heapfree");

entry("showalloclist");
entry("showfreelist");

entry("getblock");

entry("writeToHeap");